#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2270588361616
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.8404808  0.93000148 0.28398196]
  [0.78506588 0.96428213 0.91869777]
  [0.90081076 0.20421428 0.52167005]]

 [[0.32475777 0.20329261 0.87974131]
  [0.76057995 0.03147444 0.52758117]
  [0.88582912 0.67191135 0.93388511]]

 [[0.14864573 0.27438867 0.73684316]
  [0.10718746 0.37283031 0.94078603]
  [0.38745174 0.23283967 0.97046642]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.06232682776253928 0.9979410254559282


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.49971679574249805


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
Z = np.ones((4,4))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [20]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [22]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [23]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [24]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [25]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [26]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.60768273  0.16937441  1.81603422  0.47273474  1.01147155]
 [-0.54585046 -0.13063216  1.2595239  -1.87219947  0.07972988]
 [-0.26051121 -0.69162324  0.42411322 -0.34424479  0.13196936]
 [-0.51843832  1.83690961 -0.3720482  -1.57382711 -0.40444746]
 [ 1.0068514  -1.33428254 -1.57955053  1.10819078  0.91843516]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [34]:
Z = np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z)
# Z<Z>Z is illegal"

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [35]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\habib\AppData\Local\Temp\ipykernel_18116\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\habib\AppData\Local\Temp\ipykernel_18116\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\habib\AppData\Local\Temp\ipykernel_18116\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [36]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ -5. -10.  -4.   3.  -3.   6.  -8.   6.  -5.  -7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [37]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 5 6 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [38]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

_ = np.seterr(**defaults)

with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [40]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\habib\AppData\Local\Temp\ipykernel_18116\2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [41]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [10]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [42]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [43]:
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))

[1. 0. 3. 7. 2. 2. 6. 1. 5. 9.]
[1. 0. 3. 7. 2. 2. 6. 1. 5. 9.]
[1. 0. 3. 7. 2. 2. 6. 1. 5. 9.]
[1 0 3 7 2 2 6 1 5 9]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [44]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [51]:
def generate(): 
    for x in range(10):
        yield x
        Y = np.fromiter(generate(),dtype=float,count=-1)
        print(Y)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [52]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [56]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.01725867 0.04506032 0.13976131 0.2002307  0.59797726 0.64644932
 0.6635527  0.73457342 0.90553706 0.92129351]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [57]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [58]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [59]:
Z = np.zeros(10)
Z.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [60]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.91898078 0.92640256 0.86413216 0.75584296 0.64612137 0.2103705
 0.99113268 1.15613298 0.29543196 0.99474831]
[0.37710024 0.3997456  0.96938642 1.05807558 1.07051037 0.81229316
 0.88928936 0.78981243 0.43558804 0.69524646]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [61]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.56795345 0.         0.68563441 0.42501353 0.13539207 0.67158054
 0.14864771 0.94728971 0.50865051 0.07403833]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [62]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [63]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [65]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min, np.iinfo(dtype).max)
    for dtype in [np.float32, np.float64]:
       print(np.finfo(dtype).min, np.finfo(dtype).max)

-128 127
-3.4028235e+38 3.4028235e+38
-1.7976931348623157e+308 1.7976931348623157e+308
-2147483648 2147483647
-3.4028235e+38 3.4028235e+38
-1.7976931348623157e+308 1.7976931348623157e+308
-9223372036854775808 9223372036854775807
-3.4028235e+38 3.4028235e+38
-1.7976931348623157e+308 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [66]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [67]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

64


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [68]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]), ('color',    [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])

C:\Users\habib\AppData\Local\Temp\ipykernel_18116\3750984445.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]), ('color',    [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [69]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.34581772 0.32992528 0.51301909 0.10927152 0.8079613
  0.54956892 0.65457581 0.65399856 0.34705522]
 [0.34581772 0.         0.15738121 0.42607387 0.23797082 0.46272448
  0.29609768 0.36367391 0.32097406 0.24638696]
 [0.32992528 0.15738121 0.         0.27377837 0.22950263 0.54478849
  0.22001857 0.32588988 0.44134816 0.08915937]
 [0.51301909 0.42607387 0.27377837 0.         0.44697533 0.69007447
  0.2498499  0.3507156  0.64876267 0.19443396]
 [0.10927152 0.23797082 0.22950263 0.44697533 0.         0.70067688
  0.44914977 0.55013493 0.55146057 0.2636312 ]
 [0.8079613  0.46272448 0.54478849 0.69007447 0.70067688 0.
  0.44040621 0.35927731 0.1865652  0.60910565]
 [0.54956892 0.29609768 0.22001857 0.2498499  0.44914977 0.44040621
  0.         0.11840861 0.41703734 0.22579502]
 [0.65457581 0.36367391 0.32588988 0.3507156  0.55013493 0.35927731
  0.11840861 0.         0.38397415 0.34306416]
 [0.65399856 0.32097406 0.44134816 0.64876267 0.55146057 0.1865652
  0.41703734 0.3839741

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [70]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [71]:
from io import StringIO
s = StringIO('1, 2, 3, 4, 5\\n6,  ,  , 7, 8\\n ,  , 9,10,11\\n')
Z = np.genfromtxt(s, delimiter=',', dtype=np.int_)
print(Z)

[ 1  2  3  4 -1 -1 -1  7 -1 -1  9 10 -1]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [72]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
    for index in np.ndindex(Z.shape):
        print(index, Z[index])

(0, 0) 0
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 1) 1
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 2) 2
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(1, 0) 3
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(1, 1) 4
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(1, 2) 5
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(2, 0) 6
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(2, 1) 7
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [73]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [74]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [75]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.18918893  0.28914492 -0.30881141  0.36289532 -0.01164948 -0.34518083
   0.42685007 -0.05780404 -0.10735957 -0.05889605]
 [ 0.02019562 -0.05833988  0.1628449   0.16413392 -0.50608314 -0.22645638
   0.18604358  0.05983003  0.14346713  0.05436423]
 [ 0.2499114  -0.14543694  0.11902607  0.2596855   0.3552808  -0.32083841
   0.27099987 -0.34578898 -0.46863498  0.02579566]
 [ 0.18126116 -0.29030208 -0.23572537  0.1084686   0.56508218  0.30769937
  -0.0834821  -0.30256743 -0.29883573  0.0484014 ]
 [ 0.33063203  0.05754169 -0.06913637  0.31427753 -0.5996983   0.02357425
  -0.43250396 -0.09636686  0.19586295  0.27581705]]


#### 59. How to sort an array by the nth column? (★★☆)

In [76]:
Z = np.random.randint(0,10,(3,3))
print(Z[Z[:,1].argsort()])

[[8 6 8]
 [4 6 7]
 [3 8 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [77]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [78]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.41331358450164546


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [79]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [80]:
class NameArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
        def __array_finalize__(self, obj):
            if obj is None: return
            self.info = getattr(obj, 'name', "no name")
            Z = NameArray(np.arange(10), "test_name")
            print(Z.name)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [81]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[4. 3. 1. 3. 1. 3. 3. 4. 6. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [82]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [83]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3), dtype=np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
print(len(colors))

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [84]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[36 50 71 54]
 [53 43 41 80]
 [55 47 70 57]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [85]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.52404603 0.21245927 0.51702264 0.28209089 0.59193909 0.50746222
 0.47273771 0.40744962 0.38795088 0.51045735]


#### 69. How to get the diagonal of a dot product? (★★★)

In [86]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(np.diag(np.dot(A, B)))

[1.01650418 1.66067616 1.14632657 1.88790444 0.87062831]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [87]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [88]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [89]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [90]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  5) ( 0, 79) ( 5, 79) ( 7, 18) ( 7, 53) (15, 52) (15, 70) (18, 53)
 (19, 66) (19, 84) (27, 47) (27, 70) (35, 51) (35, 90) (39, 59) (39, 79)
 (47, 70) (51, 90) (52, 70) (59, 79) (66, 70) (66, 82) (66, 84) (67, 70)
 (67, 76) (70, 76) (70, 82) (75, 83) (75, 87) (83, 87)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [91]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [94]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
    Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [95]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [96]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.79974814,  0.18111062, -0.15706014, -0.4827829 , -0.24695757,
        0.38977955, -0.50479503,  0.08166157,  0.31167571,  0.40848791,
        0.39438385,  0.61528912,  0.89002958, -0.72060625,  0.47890871,
       -0.21130873, -0.42313788, -0.61546386,  0.53992751,  0.04246693,
       -0.67648209, -0.44587531, -0.41634092,  0.34266146,  0.85446755,
       -0.06360472,  0.89799584,  0.0105611 ,  0.36946232, -0.20005315,
       -0.32772181,  0.75752495, -0.01405947,  0.33764518, -0.8582047 ,
       -0.3050336 , -0.54899396, -0.18652819,  0.15210274,  0.97923886,
        0.19114546, -0.68799711,  0.85622025, -0.55424353,  0.45542391,
       -0.76946606,  0.58790955,  0.37962288,  0.6671124 ,  0.26189617,
       -0.50633453,  0.86828019,  0.42962102,  0.00630653,  0.28596853,
        0.51006384,  0.29540959,  0.1369468 ,  0.4287811 ,  0.01672821,
        0.33034598, -0.04718176, -0.33574509, -0.58677604, -0.64503767,
       -0.06166036,  0.6371662 , -0.52045102, -0.79809755,  0.29

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [98]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[14.02175283 15.40650887  1.12499173  2.17263226  5.73040326  1.92230795
  0.91266756 14.57200376  3.30175326  1.23928901]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [99]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[10.54996019 12.0001709   5.11294579  8.68492383  9.76549475  5.17326342
   6.40171505  3.71959012  0.10033503  6.00924727]
 [12.30595649 11.24183828  3.39041337  8.72754673 11.04208091  8.06808119
   8.53536486  4.41698501  2.76219564  5.89174445]
 [ 9.33600092  8.44652727  1.36734526  5.59961418  7.88733683  7.36124142
   5.83048481  1.19707256  3.24543514  2.81087229]
 [ 8.35759838  7.39752022  0.54576353  4.47314608  6.8167736   7.26002147
   4.96780708  0.07221135  3.56128179  1.6928762 ]
 [ 4.26692126  0.44845894  7.07782077  2.82948153  1.49598377 10.39139689
   2.12785732  6.36208522  9.11187321  5.76419435]
 [ 3.55379808  4.33888596  2.30064066  1.96274687  3.84533617  3.94975291
   7.68731996  8.76261745  4.46699453  4.1069374 ]
 [ 8.43495717  3.3537893   4.38474776  1.46981698  5.89388484 11.50736245
   5.95063581  1.90364832  8.58124241  1.53756302]
 [ 3.90858679  1.06065342  1.50521262  4.54277582  4.94105731  1.00949974
   7.357878   10.62046255  0.80979731  6.84290564]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [100]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[tuple(r)] = Z[tuple(z)]
print(Z)
print(R)

[[3 0 7 4 4 5 4 6 9 3]
 [4 5 6 0 8 4 0 9 8 5]
 [7 9 1 3 2 9 8 4 6 6]
 [1 0 7 8 2 7 1 4 1 9]
 [7 8 8 4 2 2 9 8 0 4]
 [6 0 9 4 9 6 2 3 7 4]
 [8 4 0 4 9 3 0 3 4 1]
 [3 5 8 6 1 6 9 7 9 4]
 [7 2 7 1 2 0 7 0 2 9]
 [7 6 9 5 6 4 7 0 9 6]]
[[0 0 0 0 0]
 [0 3 0 7 4]
 [0 4 5 6 0]
 [0 7 9 1 3]
 [0 1 0 7 8]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [101]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [102]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [103]:
Z = np.random.randint(0, 10, 50)
most_frequent = np.bincount(Z).argmax()
print(most_frequent)

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [104]:
from numpy.lib.stride_tricks import sliding_window_view
Z = np.random.randint(0, 100, (10, 10))
blocks = sliding_window_view(Z, window_shape=(3, 3))
print(blocks.shape)

(8, 8, 3, 3)


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [105]:
class Symmetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symmetric, self).__setitem__((i, j), value)
        super(Symmetric, self).__setitem__((j, i), value)

def create_symmetric(Z):
    sym_matrix = Z + Z.T - np.diag(Z.diagonal())
    return np.asarray(sym_matrix).view(Symmetric)
Z = np.random.randint(0, 10, (5, 5))
S = create_symmetric(Z)

print("Initial Symmetric Matrix:")
print(S)
S[2, 3] = 999

print("\nMatrix after setting S[2, 3] = 999:")
print(S) 

Initial Symmetric Matrix:
[[ 7  9 13  2  6]
 [ 9  7 13  3 13]
 [13 13  2 14  8]
 [ 2  3 14  2 12]
 [ 6 13  8 12  3]]

Matrix after setting S[2, 3] = 999:
[[  7   9  13   2   6]
 [  9   7  13   3  13]
 [ 13  13   2 999   8]
 [  2   3 999   2  12]
 [  6  13   8  12   3]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [106]:
p, n = 10, 20
M = np.random.uniform(0, 1, (p, n, n))
V = np.random.uniform(0, 1, (p, n, 1))
result = np.einsum('pij,pjk->ik', M, V)
print(result.shape)

(20, 1)


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [107]:
Z = np.ones((16, 16))
k = 4
block_sum = Z.reshape(Z.shape[0]//k, k, Z.shape[1]//k, k).sum(axis=(1, 3))

print(block_sum.shape)  
print(block_sum)      

(4, 4)
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [108]:
def iterate(Z):
    N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] +
         Z[1:-1, 0:-2]                 + Z[1:-1, 2:] +
         Z[2:  , 0:-2] + Z[2:  , 1:-1] + Z[2:  , 2:])
    
    birth = (N == 3) & (Z[1:-1, 1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1, 1:-1] == 1)
    
    Z[...] = 0
    Z[1:-1, 1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0, 2, (10, 10))

for _ in range(5): 
    Z = iterate(Z)

print(Z)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0]
 [0 0 1 1 0 1 1 0 0 0]
 [0 1 1 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [109]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
result = Z[np.argpartition(Z, -n)[-n:]]
print(result)

[9995 9997 9999 9996 9998]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [110]:
def cartesian_numpy(*arrays):
    grid = np.meshgrid(*arrays, indexing='ij')
    return np.stack(grid, axis=-1).reshape(-1, len(arrays))
v1 = np.array([1, 2])
v2 = np.array([3, 4])
v3 = np.array([5, 6])
result = cartesian_numpy(v1, v2, v3)
print(result)

[[1 3 5]
 [1 3 6]
 [1 4 5]
 [1 4 6]
 [2 3 5]
 [2 3 6]
 [2 4 5]
 [2 4 6]]


#### 91. How to create a record array from a regular array? (★★★)

In [111]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats='S8, f8, i8')
print("Record Array:")
print(R)
print("\nAccessing 'col1' via attribute:")
print(R.col1)
print("\nAccessing 'col2' via attribute:")
print(R.col2)

Record Array:
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]

Accessing 'col1' via attribute:
[b'Hello' b'World']

Accessing 'col2' via attribute:
[2.5 3.6]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [112]:
import time
Z = np.random.rand(5000000)
start = time.time()
res1 = Z * Z * Z
print(f"Direct multiplication time: {time.time() - start:.5f} seconds")
start = time.time()
res2 = np.power(Z, 3)
print(f"np.power time:{time.time() - start:.5f} seconds")
start = time.time()
res3 = np.einsum('i,i,i->i', Z, Z, Z)
print(f"np.einsum time:{time.time() - start:.5f} seconds")
print("\nResults match:", np.allclose(res1, res2) and np.allclose(res1, res3))

Direct multiplication time: 0.04702 seconds
np.power time:0.12484 seconds
np.einsum time:0.03310 seconds

Results match: True


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [113]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))
matches = np.logical_and.reduce([np.isin(A, b).any(axis=1) for b in B])
rows = np.where(matches)[0]
print("Matching row indices of A:", rows)

Matching row indices of A: [3 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [114]:
Z = np.random.randint(0, 2, (10, 3))
mask = Z.max(axis=1) != Z.min(axis=1)
result = Z[mask]
print("Original Matrix:\n", Z)
print("\nRows with unequal values:\n", result)

Original Matrix:
 [[0 1 1]
 [0 1 1]
 [1 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 1]]

Rows with unequal values:
 [[0 1 1]
 [0 1 1]
 [1 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [115]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
bits = 8
binary_matrix = ((I.reshape(-1, 1) >> np.arange(bits)[::-1]) & 1)

print(binary_matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [116]:
Z = np.array([[1, 2, 3],
              [4, 5, 6],
              [1, 2, 3],
              [7, 8, 9],
              [4, 5, 6]])

unique_rows = np.unique(Z, axis=0)

print("Original Array:")
print(Z)

print("\nUnique Rows:")
print(unique_rows)

Original Array:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]

Unique Rows:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [117]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
inner_eq = np.einsum('i,i->', A, B)
outer_eq = np.einsum('i,j->ij', A, B)
sum_eq = np.einsum('i->', A)
mul_eq = np.einsum('i,i->i', A, B)


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [118]:
phi = np.arange(0, 10 * np.pi, 0.5)
X = phi * np.cos(phi)
Y = phi * np.sin(phi)
dx = np.diff(X)
dy = np.diff(Y)
distances = np.sqrt(dx**2 + dy**2)
cumulative_distance = np.insert(np.cumsum(distances), 0, 0)
num_samples = 200
equidistant_steps = np.linspace(0, cumulative_distance[-1], num_samples)
X_sampled = np.interp(equidistant_steps, cumulative_distance, X)
Y_sampled = np.interp(equidistant_steps, cumulative_distance, Y)
print(f"Original number of points: {len(X)}")
print(f"New number of equidistant points: {len(X_sampled)}")

Original number of points: 63
New number of equidistant points: 200


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [119]:
X = np.array([[1.0, 0.0, 3.0, 8.0],   
              [2.0, 0.0, 1.0, 1.0],   
              [1.5, 2.5, 0.0, 0.0],     
              [5.0, -1.0, 0.0, 0.0]]) 
n = 4
is_integer = np.all(np.mod(X, 1) == 0, axis=1)
sums_to_n = (np.sum(X, axis=1) == n)
is_non_negative = np.all(X >= 0, axis=1)
valid_rows = is_integer & sums_to_n & is_non_negative
result = X[valid_rows]
print("Original Matrix:\n", X)
print(f"\nRows that sum to {n} and contain only non-negative integers:\n", result)

Original Matrix:
 [[ 1.   0.   3.   8. ]
 [ 2.   0.   1.   1. ]
 [ 1.5  2.5  0.   0. ]
 [ 5.  -1.   0.   0. ]]

Rows that sum to 4 and contain only non-negative integers:
 [[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [120]:
X = np.random.randn(100)
N = 1000
bootstrap_samples = np.random.choice(X, size=(N, len(X)), replace=True)
bootstrap_means = np.mean(bootstrap_samples, axis=1)
confidence_interval = np.percentile(bootstrap_means, [2.5, 97.5])
print("Original Array Mean:", np.mean(X))
print("Bootstrapped 95% Confidence Interval:", confidence_interval)

Original Array Mean: 0.15702917882775388
Bootstrapped 95% Confidence Interval: [-0.01769963  0.330093  ]
